const quizData = [
  {
    question: "What does HTML stand for?",
    a: "Hyper Trainer Marking Language",
    b: "Hyper Text Marketing Language",
    c: "Hyper Text Markup Language",
    d: "Hyper Text Markup Leveler",
    correct: "c",
  },
  {
    question: "Which of the following is not a programming language?",
    a: "TypeScript",
    b: "Python",
    c: "Anaconda",
    d: "Rupee",
    correct: "c",
  },
  {
    question: "Python is _____ programming language.",
    a: "high-level",
    b: "mid-level",
    c: "low-level",
    d: "none of the above",
    correct: "a",
  },
  {
    question: "Which of the following includes Chrome's V8 JavaScript Engine?",
    a: "jQuery",
    b: "Java",
    c: "npm",
    d: "Node.js",
    correct: "d",
  },
  {
    question: "Choose the correct HTML tag for the largest heading",
    a: "<heading>",
    b: "<h6>",
    c: "<head>",
    d: "<h1>",
    correct: "d",
  },
  {
    question: "What is the correct HTML tag for inserting a line break?",
    a: "<br>",
    b: "<lb>",
    c: "<break>",
    correct: "a",
  },
  {
    question: "What is the correct HTML for creating a hyperlink?",
    a: "<a url='http://www.w3schools.com'>W3Schools.com</a>",
    b: "<a name='http://www.w3schools.com'>W3Schools.com</a>",
    c: "<a href='http://www.w3schools.com'>W3Schools</a",
    d: "<a>http://www.w3schools.com</a>",
    correct: "c",
  },
  {
    question: "Which of these tags are all <table> tags?",
    a: "<table> <head> <tfoot>",
    b: "<table> <tr> <td>",
    c: "<thead> <body> <tr>",
    d: "<table> <tr> <tt>",
    correct: "b",
  },
];
